version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sinon
    versions:
    - 10.0.0
    - 9.2.4
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: mock-fs
    versions:
    - 4.13.0
  - dependency-name: grunt
    versions:
    - 1.3.0
